<?php
$title = 'Create a new post';
$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>
<?php


$title = $form->get('title');
$title->setAttribute('class', 'form-control');
$title->setAttribute('placeholder', 'Post title');


$text = $form->get('text');
$text->setAttribute('class', 'form-control');
$text->setAttribute('placeholder', 'Text');


$submit = $form->get('submit');
$submit->setAttribute('class', 'btn btn-primary');

$form->setAttribute('action', $this->url('blog', ['action' => 'add']));
$form->prepare();

echo $this->form()->openTag($form);
?>
<?php
?>
<div class="form-group">
    <?= $this->formLabel($title) ?>
    <?= $this->formElement($title) ?>
    <?= $this->formElementErrors()->render($title, ['class' => 'help-block']) ?>
</div>

<div class="form-group">
    <?= $this->formLabel($text) ?>
    <?= $this->formElement($text) ?>
    <?= $this->formElementErrors()->render($text, ['class' => 'help-block']) ?>
</div>

<?php
echo $this->formSubmit($submit);
echo $this->formHidden($form->get('id'));
echo $this->form()->closeTag();