<?php


$title = 'Latest Posts';
$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>
<p>
    <a href="<?= $this->url('blog', ['action' => 'add']) ?>">Create a new post</a>
</p>


<style>
.post {
    border-radius: 25px;
    background: whitesmoke;
    padding: 20px;
    width: 200px;
    height: 150px;
}
</style>



<?php foreach ($posts as $post) : ?>
<dl class="post">
    <dd><b><?= $this->escapeHtml($post->title) ?></b></dd>
    <dd><?= $this->escapeHtml($post->text) ?></dd>
    <dd>
        <a href="<?= $this->url('blog', ['action' => 'edit', 'id' => $blog->id]) ?>">Edit</a>
        <a href="<?= $this->url('blog', ['action' => 'delete', 'id' => $blog->id]) ?>">Delete</a>
    </dd>
</dl>

<?php endforeach; ?>