<?php


$title = 'Latest Posts';
$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>
<p>
    <a href="<?= $this->url('blog', ['action' => 'add']) ?>">Create a new post</a>
</p>


<style>
.post {
    border-radius: 25px;
    background: whitesmoke;
    padding: 20px;
    width: 90%;

}
</style>



<?php foreach ($posts as $post) : ?>
<dl class="post">
    <dd><b><?= $this->escapeHtml($post->title) ?></b></dd>
    <dd><?= $this->escapeHtml($post->text) ?></dd>
    <dd>
        <p> <a href="<?= $this->url('comment', ['id' => $post->postID]) ?>">Comment</a></p>

        <a href="<?= $this->url('blog', ['action' => 'edit', 'postID' => $post->postID]) ?>">Edit</a>
        <a href="<?= $this->url('blog', ['action' => 'delete',  'postID' => $post->postID]) ?>">Delete</a>
    </dd>
</dl>

<?php endforeach; ?>